services:
    backend-database:
        container_name: movies-backend-database
        hostname: mariadb
        build: ./backend-database
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        environment:
            MARIADB_ROOT_PASSWORD: abc123
        volumes:
            - mariadbdata:/var/lib/mysql

    backend:
        container_name: movies-backend
        depends_on:
            - backend-database
        build: ./backend
        ports:
            - "8080:80"
            - "7070:7070"

    dozzle:
        container_name: dozzle
        hostname: dozzle
        image: amir20/dozzle
        ports:
            - "8300:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

volumes:
    mariadbdata:
